<!doctype html>
<html lang="en">
    <head>
        <?php include __DIR__ . '/includes/head.phtml' ?>
    </head>

    <body>
        <div class="min-h-full">
            <nav>
                <div class="nav-wrapper">
                    <div class="flex items-center">
                        <a href="/">Home</a>
                        <a href="/products">Products</a>
                        <a href="/contact">Contact</a>
                    </div>
                </div>
            </nav>
        </div>
    </body>
</html>