<!doctype html>
<html lang="en" class="h-full bg-gray-100">
    <head>
        <?php include __DIR__ . '/includes/head.phtml' ?>
    </head>
    <body class="h-full">
        <div class="min-h-full">
            <nav class="bg-gray-800">
                <div class="mx-auto max-w-7xl px4">
                    <div class="flex items-center justify-start gap-4 h-16">
                        <a href="/"
                           class="text-white py-2 px-3 leading-lg rounded-md hover:bg-gray-900 transition transition-all duration-[0.5s]">
                            Home
                        </a>

                        <a href="/products"
                           class="text-white py-2 px-3 leading-lg rounded-md hover:bg-gray-900 transition transition-all duration-[0.5s]">
                            Products
                        </a>

                        <a href="/contact"
                           class="text-white py-2 px-3 leading-lg rounded-md hover:bg-gray-900 transition transition-all duration-[0.5s]">
                            Contact
                        </a>
                    </div>
                </div>
            </nav>

            <header>
                <div class="container">
                    <h1 id="page-title">Home</h1>
                </div>
            </header>

            <main>
                <div class="container" style="padding: 2rem 0">
                    My main content here
                </div>
            </main>
        </div>
    </body>
</html>